// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: DeleteAllUsers.sql

package database

import (
	"context"
)

const deleteAllUser = `-- name: DeleteAllUser :exec
DELETE FROM users
`

func (q *Queries) DeleteAllUser(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllUser)
	return err
}
